create table Person_Reader
(
    reader_id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar(100) not null,
    year_of_birthday int check ( year_of_birthday > 1900 )
);

create table Book(
                     book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                     reader_id int not null REFERENCES Person_Reader(reader_id) on delete set null ,
                     book_name varchar(200) not null UNIQUE,
                     author varchar(100) not null  ,
                     year_of_production int not null
);

insert into Person_Reader(name, year_of_birthday) VALUES ('Иванов Иван Иванович', 1953);
insert into Person_Reader(name, year_of_birthday) VALUES ('Григорьев Святослав Сергеевич', 1989);
insert into Person_Reader(name, year_of_birthday) VALUES ('Грибков Роман Александрович', 2000);
insert into Person_Reader(name, year_of_birthday) VALUES ('Кузьмин Александр Владимирович', 1984);

insert into Book(reader_id, book_name, author, year_of_production) VALUES (1,'Желание купить канары','Смоляницын Евгений',2020);
insert into Book(reader_id, book_name, author, year_of_production) VALUES (2,'Морской Слон возвращается','Курской Дамир',1944);
insert into Book(reader_id, book_name, author, year_of_production) VALUES (3,'Попы и йети','Невменяемый Таймыр',2003);
insert into Book(reader_id, book_name, author, year_of_production) VALUES (4,'Основа песков Египта','Невменяемый Таймыр',2007);
insert into Book(reader_id, book_name, author, year_of_production) VALUES (1,'Как победить единорога','Суровый Поц',2021);
insert into Book(reader_id, book_name, author, year_of_production) VALUES (1,'Математические способности божьих коровок ','Идиатулин Семен',1812);

select * from Person_Reader;
select * from Book;

select * from Person_Reader join Book B on Person_Reader.reader_id = B.reader_id;
select Person_Reader.name,book_name,year_of_production from Person_Reader join Book B on Person_Reader.reader_id = B.reader_id;

drop table Book;
drop table Person_Reader;